- vds-frontend/src/App.scss
- vds-frontend/src/components/informationModal/CheckinMessage.js
- vds-frontend/src/components/informationModal/InformationModal.jsx
- vds-frontend/src/components/informationModal/Loader.js
- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/header/Header.jsx
- vds-frontend/src/services/Utils.js
This PR includes changes related to adding API call while navigating to Dashboard page from Information modal page and adding a new button to Information modal page which will redirect us to dashboard page
> CIE-726  Navigating to home page within 30 sec timeout of host driven scan mode greys out DL buttons

- vds-frontend/src/App.scss
- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/settings/Settings.jsx
This PR includes changes related to adding spinner before reader info API and alert box on failure of get reader info API for dashboard and settings page.
> CIE-796 Retry HTTP API for reader/info API till we get success 200 response from reader/info API

- vds-frontend/src/App.scss
- vds-frontend/src/components/informationModal/InformationModal.jsx
- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes below changes:
1. Moving the cancel button and make it bigger for both physical and mDL.
2. Age check profile implementatation
> CIE-800 [VDS Demo-App] Move the cancel button next to the GIF and make it bigger like squared shaped

- vds-frontend/src/components/informationModal/InformationModal.jsx
- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes changes related to check in message issue for Age check scenario
> Check in message issue for Age check

- vds-frontend/src/components/informationModal/InformationModal.jsx
- vds-frontend/src/containers/dashboard/Dashboard.jsx
this PR is raised for check in message showing on check in page
> Check in message issue changes revert

- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes changes related to showing a message on Dashboard page on the basis of connection status.
> CIE-808 [VDS Demo-App] Show message on screen when device is in USB_DEBUG_ENABLED/DISABLED state

- vds-frontend/src/components/informationModal/InformationModal.jsx
- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/settings/Settings.jsx
This PR includes below changes:
1. Invoking stop API on settings page load only if user navigates from information modal page.
> CIE-809 [VDS Demo-App] Reader info API failing on button click from settings page if user navigates from information modal page to settings page

- vds-frontend/src/containers/settings/Settings.jsx
- vds-frontend/src/services/Utils.js
This PR includes changes related to adding reader profile radio buttons and change reader profile functionality.
> reader profile changes on settings page

- vds-frontend/src/App.scss
- vds-frontend/src/components/informationModal/InformationModal.jsx
This PR includes changes related to adding message at the bottom of information modal.
> adding message at the bottom of information modal done

- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes changes related to error handling in SSE with event listener
> CIE-825 [VDS Demo-App] Error handling on failure of Server sent events in HOLDER_DRIVEN Mode

- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes changes required to close SSE connection on page navigation/ page unmounting.
> CIE-842 [VDS Demo] SSE Read is being called multiple times from UI

- vds-frontend/src/containers/dashboard/Dashboard.jsx
This PR includes changes in implementation approach.
> [VDS Demo] SSE Read is being called multiple times from UI

- vds-frontend/src/containers/settings/Settings.jsx
This PR includes changes related to loader icon missing when user clicks on Settings button. We have added loader of 1 seconds while navigating to settings page.
> CIE-828 [VDS-Demo] Loader icon missing when user clicks on settings button

- vds-frontend/package.json
- vds-frontend/src/App.scss
- vds-frontend/src/containers/settings/Settings.jsx
- vds-frontend/src/services/Utils.js
Created new UI for the settings page.
> Feature/new settings UI

- vds-frontend/src/App.scss
- vds-frontend/src/containers/settings/Settings.jsx
> Fixing the spinning loaders

- vds-frontend/src/App.scss
- vds-frontend/src/containers/header/Header.jsx
- vds-frontend/src/containers/settings/Settings.jsx
Made settings page responsive, and fixed loader.
> Feature/new settings page UI

- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/settings/Settings.jsx
Fixed the Reader Profile radio button issue
> Fixed the Reader Profile radio button issue

- vds-frontend/src/containers/settings/Settings.jsx
Resolved the Reader Profile radio input issue. Now it will be auto-filled based on the API response and on changing the input, it is working as expected.
> Resolved the Reader profile radio input issue.

- vds-frontend/src/App.scss
- vds-frontend/src/containers/header/Header.jsx
- vds-frontend/src/containers/settings/Settings.jsx
- vds-frontend/src/services/Utils.js
Fixed the Wi-Fi payload and some header styles.
> Fixed the Wi-Fi payload and some header styles

- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/settings/Settings.jsx
removed the reload windows popup feature.
> removed the reload window error popup feature.

- vds-frontend/src/containers/dashboard/Dashboard.jsx
Fix for appointment time issue on the HOLDER_MODE.
> Appointment time fix for HOLDER_MODE

- vds-frontend/src/containers/dashboard/Dashboard.jsx
- vds-frontend/src/containers/header/Header.jsx
> Logo and title changes

- vds-backend/package.json
> Added the Axios in backend
